version: '3'

services:
  db:
    restart: always
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TestingThis0ut
      - MSSQL_PID=Express
    ports:
      - "1433:1433"

volumes:
  mssql_data:
